<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

<h1 align="center"><font size="5">Final Project: Classification with Python</font></h1>


<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
    <li><a href="https://#Section_1">Instructions</a></li>
    <li><a href="https://#Section_2">About the Data</a></li>
    <li><a href="https://#Section_3">Importing Data </a></li>
    <li><a href="https://#Section_4">Data Preprocessing</a> </li>
    <li><a href="https://#Section_5">One Hot Encoding </a></li>
    <li><a href="https://#Section_6">Train and Test Data Split </a></li>
    <li><a href="https://#Section_7">Train Logistic Regression, KNN, Decision Tree, SVM, and Linear Regression models and return their appropriate accuracy scores</a></li>
</a></li>
</div>
<p>Estimated Time Needed: <strong>180 min</strong></p>
</div>

<hr>


# Instructions


In this notebook, you will  practice all the classification algorithms that we have learned in this course.


Below, is where we are going to use the classification algorithms to create a model based on our training data and evaluate our testing data using evaluation metrics learned in the course.

We will use some of the algorithms taught in the course, specifically:

1. Linear Regression
2. KNN
3. Decision Trees
4. Logistic Regression
5. SVM

We will evaluate our models using:

1.  Accuracy Score
2.  Jaccard Index
3.  F1-Score
4.  LogLoss
5.  Mean Absolute Error
6.  Mean Squared Error
7.  R2-Score

Finally, you will use your models to generate the report at the end. 


# About The Dataset


The original source of the data is Australian Government's Bureau of Meteorology and the latest data can be gathered from [http://www.bom.gov.au/climate/dwo/](http://www.bom.gov.au/climate/dwo/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01).

The dataset to be used has extra columns like 'RainToday' and our target is 'RainTomorrow', which was gathered from the Rattle at [https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData](https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)




This dataset contains observations of weather metrics for each day from 2008 to 2017. The **weatherAUS.csv** dataset includes the following fields:

| Field         | Description                                           | Unit            | Type   |
| ------------- | ----------------------------------------------------- | --------------- | ------ |
| Date          | Date of the Observation in YYYY-MM-DD                 | Date            | object |
| Location      | Location of the Observation                           | Location        | object |
| MinTemp       | Minimum temperature                                   | Celsius         | float  |
| MaxTemp       | Maximum temperature                                   | Celsius         | float  |
| Rainfall      | Amount of rainfall                                    | Millimeters     | float  |
| Evaporation   | Amount of evaporation                                 | Millimeters     | float  |
| Sunshine      | Amount of bright sunshine                             | hours           | float  |
| WindGustDir   | Direction of the strongest gust                       | Compass Points  | object |
| WindGustSpeed | Speed of the strongest gust                           | Kilometers/Hour | object |
| WindDir9am    | Wind direction averaged of 10 minutes prior to 9am    | Compass Points  | object |
| WindDir3pm    | Wind direction averaged of 10 minutes prior to 3pm    | Compass Points  | object |
| WindSpeed9am  | Wind speed averaged of 10 minutes prior to 9am        | Kilometers/Hour | float  |
| WindSpeed3pm  | Wind speed averaged of 10 minutes prior to 3pm        | Kilometers/Hour | float  |
| Humidity9am   | Humidity at 9am                                       | Percent         | float  |
| Humidity3pm   | Humidity at 3pm                                       | Percent         | float  |
| Pressure9am   | Atmospheric pressure reduced to mean sea level at 9am | Hectopascal     | float  |
| Pressure3pm   | Atmospheric pressure reduced to mean sea level at 3pm | Hectopascal     | float  |
| Cloud9am      | Fraction of the sky obscured by cloud at 9am          | Eights          | float  |
| Cloud3pm      | Fraction of the sky obscured by cloud at 3pm          | Eights          | float  |
| Temp9am       | Temperature at 9am                                    | Celsius         | float  |
| Temp3pm       | Temperature at 3pm                                    | Celsius         | float  |
| RainToday     | If there was rain today                               | Yes/No          | object |
| RainTomorrow  | If there is rain tomorrow                             | Yes/No          | float  |

Column definitions were gathered from [http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml](http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)



## **Import the required libraries**


In [54]:
# All Libraries required for this lab are listed below. The libraries pre-installed on Skills Network Labs are commented.
# !mamba install -qy pandas==1.3.4 numpy==1.21.4 seaborn==0.9.0 matplotlib==3.5.0 scikit-learn==0.20.1
# Note: If your environment doesn't support "!mamba install", use "!pip install"

In [55]:
# Surpress warnings:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

In [56]:
#you are running the lab in your  browser, so we will install the libraries using ``piplite``
# import piplite
# await piplite.install(['pandas'])
# await piplite.install(['numpy'])


In [57]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

### Importing the Dataset


In [58]:
# from pyodide.http import pyfetch

# async def download(url, filename):
#     response = await pyfetch(url)
#     if response.status == 200:
#         with open(filename, "wb") as f:
#             f.write(await response.bytes())

In [59]:
#path='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv'

In [60]:
# await download(path, "Weather_Data.csv")
# filename ="Weather_Data.csv"

In [61]:
df = pd.read_csv(r"C:\Users\Satyndra Gautam\Desktop\Data Science and Machine Learning with Python\Machine Learning Models or Algorithms\Supervised ML Models\Regression\Weather_Data.csv")
df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

### Data Preprocessing


#### One Hot Encoding


First, we need to perform one hot encoding to convert categorical variables to binary variables.


In [62]:
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])
df_sydney_processed.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0             41   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7             41   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1             41   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0             41   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0             41   

   WindSpeed9am  WindSpeed3pm  Humidity9am  ...  WindDir3pm_NNW  \
0            17            20           92  ...           False   
1             9            13           83  ...           False   
2            17             2           88  ...           False   
3            22            20           83  ...           False   
4            11             6           88  ...           False   

   WindDir3pm_NW  WindDir3pm_S  WindDir3pm_SE  WindDir3pm_SSE  WindDir3pm_SSW  \
0          False         False          False           False            True   
1          False         False          False           False           False   
2          False         False          False           False           False   
3          False         False          False           False           False   
4          False         False          False           False           False   

   WindDir3pm_SW WindDir3pm_W  WindDir3pm_WNW  WindDir3pm_WSW  
0          False        False           False           False  
1          False        False           False           False  
2          False        False           False           False  
3          False        False           False           False  
4          False         True           False           False  

[5 rows x 68 columns]

Next, we replace the values of the 'RainTomorrow' column changing them from a categorical column to a binary column. We do not use the `get_dummies` method because we would end up with two columns for 'RainTomorrow' and we do not want, since 'RainTomorrow' is our target.


In [63]:
df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)
df_sydney_processed.head()
df_sydney_processed.dtypes

Date               object
MinTemp           float64
MaxTemp           float64
Rainfall          float64
Evaporation       float64
                   ...   
WindDir3pm_SSW       bool
WindDir3pm_SW        bool
WindDir3pm_W         bool
WindDir3pm_WNW       bool
WindDir3pm_WSW       bool
Length: 68, dtype: object

### Training Data and Test Data


Now, we set our 'features' or x values and our Y or target variable.


In [64]:
df_sydney_processed.drop('Date',axis=1,inplace=True)

In [65]:
df_sydney_processed = df_sydney_processed.astype(float)
df_sydney_processed.dtypes

MinTemp           float64
MaxTemp           float64
Rainfall          float64
Evaporation       float64
Sunshine          float64
                   ...   
WindDir3pm_SSW    float64
WindDir3pm_SW     float64
WindDir3pm_W      float64
WindDir3pm_WNW    float64
WindDir3pm_WSW    float64
Length: 67, dtype: object

In [66]:
features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']
#features.head()
#Y.head()

### Linear Regression


#### Q1) Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `10`.


In [67]:
#Enter Your Code, Execute and take the Screenshot

In [68]:
x_train, x_test, y_train, y_test = train_test_split(features, Y, random_state = 10, test_size = 0.2)

print(f"""The Shape of Independent Variables (Training Set):  {x_train.shape} \n The shape of Dependent Variable (Training Set):  {y_train.shape} """ )
print(f"""The Shape of Independent Variables (Test Set):  {x_test.shape} \n The shape of Dependent Variable (Test Set):  {y_test.shape} """)

The Shape of Independent Variables (Training Set):  (2616, 66) 
 The shape of Dependent Variable (Training Set):  (2616,) 
The Shape of Independent Variables (Test Set):  (655, 66) 
 The shape of Dependent Variable (Test Set):  (655,) 


#### Q2) Create and train a Linear Regression model called LinearReg using the training data (`x_train`, `y_train`).


In [69]:
#Enter Your Code, Execute and take the Screenshot

In [70]:
LinearReg = LinearRegression()
LinearReg.fit(x_train, y_train)

LinearRegression()

#### Q3) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [71]:
#Enter Your Code, Execute and take the Screenshot

In [72]:
predictions = LinearReg.predict(x_test)
predictions[0:4]

array([0.13156128, 0.27613831, 0.97797394, 0.28764343])

#### Q4) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [73]:
#Enter Your Code, Execute and take the Screenshot

In [74]:
LinearRegression_MAE = mean_absolute_error(y_test, predictions)
LinearRegression_MSE = mean_squared_error(y_test, predictions)
LinearRegression_R2 = r2_score(y_test, predictions)

# Or we can calculate directly

LR_MAE = np.mean(np.absolute(predictions - y_test))
LR_MSE = np.mean((predictions - y_test)**2)
LR_R2 = r2_score(y_test, predictions)

#### Q5) Show the MAE, MSE, and R2 in a tabular format using data frame for the linear model.


In [75]:
#Enter Your Code, Execute and take the Screenshot

In [76]:
Report = {"Metrics":["MAE","MSE","R2"],"Result": 
    [LinearRegression_MAE,LinearRegression_MSE,LinearRegression_R2]}

# Report = {"Metrics":["MAE","MSE","R2"],"Result": 
#     [LR_MAE,LR_MSE,LR_R2]}

Report = pd.DataFrame(Report)
Report.head()

Metrics    Result
0     MAE  0.256315
1     MSE  0.115715
2      R2  0.427161

### KNN


#### Q6) Create and train a KNN model called KNN using the training data (`x_train`, `y_train`) with the `n_neighbors` parameter set to `4`.


In [77]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output

In [78]:
# Since it is not clearly mentioned if we need to convert the dataframe into array for this task, however, I am going to use array and standardize independent variables for training and testing set
KNN = KNeighborsClassifier(n_neighbors=4)

X_train = x_train.values
X_train_norm = preprocessing.StandardScaler().fit_transform(X_train.astype(float))
X_train_norm[0:1] # <------------

Y_train = y_train.values  # <------------

X_test = x_test.values
X_test_norm = preprocessing.StandardScaler().fit_transform(X_test.astype(float))
X_test_norm[0:1] # <-------------

Y_test = y_test.values # <-------------

KNN.fit(X_train_norm, Y_train)

KNeighborsClassifier(n_neighbors=4)

#### Q7) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [79]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output

In [80]:
predictions_knn = KNN.predict(X_test_norm)
predictions_knn[0:5]

array([0., 1., 1., 1., 0.])

#### Q8) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [81]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output

In [82]:
KNN_Accuracy_Score = metrics.accuracy_score(Y_test, predictions_knn)
KNN_JaccardIndex = metrics.jaccard_score(Y_test, predictions_knn)
KNN_F1_Score = metrics.f1_score(Y_test, predictions_knn, average="weighted")

### Decision Tree


#### Q9) Create and train a Decision Tree model called Tree using the training data (`x_train`, `y_train`).


In [83]:
#Enter Your Code, Execute and take the Screenshot

In [84]:
Tree = DecisionTreeClassifier(criterion="entropy", max_depth= 4)
Tree.fit(X_train_norm, Y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

#### Q10) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [85]:
#Enter Your Code, Execute and take the Screenshot

In [86]:
predictions_tree = Tree.predict(X_test_norm) 
predictions_tree[0:5]

array([0., 0., 1., 0., 0.])

#### Q11) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [87]:
#Enter Your Code, Execute and take the Screenshot

In [88]:
Tree_Accuracy_Score = metrics.accuracy_score(Y_test, predictions_tree)
Tree_JaccardIndex = metrics.jaccard_score(Y_test, predictions_tree)
Tree_F1_Score = metrics.f1_score(Y_test, predictions_tree, average="weighted")

### Logistic Regression


#### Q12) Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `1`.


In [89]:
#Enter Your Code, Execute and take the Screenshot

In [90]:
x_train, x_test, y_train, y_test = train_test_split(features.values, Y.values, test_size=0.2, random_state = 1)
x_train = preprocessing.StandardScaler().fit_transform(x_train.astype(float))
x_test = preprocessing.StandardScaler().fit_transform(x_test.astype(float))

#### Q13) Create and train a LogisticRegression model called LR using the training data (`x_train`, `y_train`) with the `solver` parameter set to `liblinear`.


In [91]:
#Enter Your Code, Execute and take the Screenshot

In [92]:
LR = LogisticRegression(solver="liblinear")
LR.fit(x_train, y_train)

LogisticRegression(solver='liblinear')

#### Q14) Now, use the `predict` and `predict_proba` methods on the testing data (`x_test`) and save it as 2 arrays `predictions` and `predict_proba`.


In [93]:
#Enter Your Code, Execute and take the Screenshot

In [94]:
predictions_log = LR.predict(x_test)
predictions_log[0:5]

array([0., 0., 0., 0., 0.])

In [95]:
predict_proba = LR.predict_proba(x_test)
predict_proba[0:5]

array([[0.75847636, 0.24152364],
       [0.97617458, 0.02382542],
       [0.50007461, 0.49992539],
       [0.88583947, 0.11416053],
       [0.97302005, 0.02697995]])

#### Q15) Using the `predictions`, `predict_proba` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [96]:
#Enter Your Code, Execute and take the Screenshot

In [97]:
LR_Accuracy_Score = metrics.accuracy_score(y_test, predictions_log)
LR_JaccardIndex = metrics.jaccard_score(y_test, predictions_log, pos_label=0)
LR_F1_Score = metrics.f1_score(y_test, predictions_log, average="binary")
LR_Log_Loss = metrics.log_loss(y_test, predict_proba)

### SVM


#### Q16) Create and train a SVM model called SVM using the training data (`x_train`, `y_train`).


In [98]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output

In [99]:
SVM = svm.SVC(kernel="poly")
SVM.fit(x_train, y_train)

SVC(kernel='poly')

#### Q17) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [100]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output

In [101]:
predictions_svm = SVM.predict(x_test)
predictions_svm[0:5] 

array([0., 0., 0., 0., 0.])

#### Q18) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [102]:
SVM_Accuracy_Score = metrics.accuracy_score(y_test, predictions_svm)
SVM_JaccardIndex = metrics.jaccard_score(y_test, predictions_svm)
SVM_F1_Score = metrics.f1_score(y_test, predictions_svm)

### Report


#### Q19) Show the Accuracy,Jaccard Index,F1-Score and LogLoss in a tabular format using data frame for all of the above models.

\*LogLoss is only for Logistic Regression Model


In [115]:
Report = {"Model Name": ["KNN", "Decision Tree", "Logistic Regression", "Support Vector Machine"],
          "Accuracy Score": [KNN_Accuracy_Score, Tree_Accuracy_Score, LR_Accuracy_Score, SVM_Accuracy_Score],
          "Jaccard Score": [KNN_JaccardIndex, Tree_JaccardIndex, LR_JaccardIndex, SVM_JaccardIndex],
          "F1 Score": [KNN_F1_Score, Tree_F1_Score, LR_F1_Score, SVM_F1_Score],
          "Log Loss": [0, 0, LR_Log_Loss, 0]
          }
Report = pd.DataFrame(Report).style.hide(axis='index') # using style and hide can eliminate the index from the dataframe
Report


<h2 id="Section_5">  How to submit </h2>

<p>Once you complete your notebook you will have to share it. You can download the notebook by navigating to "File" and clicking on "Download" button.

<p>This will save the (.ipynb) file on your computer. Once saved, you can upload this file in the "My Submission" tab, of the "Peer-graded Assignment" section.  


<h2>About the Authors:</h2> 

<a href="https://www.linkedin.com/in/joseph-s-50398b136/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01">Joseph Santarcangelo</a> has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.

### Other Contributors

[Svitlana Kramar](https://www.linkedin.com/in/svitlana-kramar/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork30654641-2022-01-01)


## Change Log

| Date (YYYY-MM-DD) | Version | Changed By    | Change Description          |
| ----------------- | ------- | ------------- | --------------------------- |
| 2022-06-22        | 2.0     | Svitlana K.   | Deleted GridSearch and Mock |

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>
